package com.auv.annotation;

public enum SerialPortCommand {

    COMMAND_CONTROL_DOOR,
    COMMAND_CONTROL_LIGHT,
    COMMAND_CONTROL_DISINFECT_LIGHT,
    COMMAND_CONTROL_INDICATOR_LIGHT,
    COMMAND_CONTROL_HEATING,
    COMMAND_CONTROL_GOODS_EXITS;
}
